#!/bin/bash

# My custom alias
alias update='sudo apt-get update && sudo apt-get upgrade -y'
alias svnreloc='svn switch --relocate'
alias desligar='sudo shutdown -h now'
alias reiniciar='sudo shutdown -r now'
alias setclip='xclip -selection c'
alias getclip='xclip -selection clipboard -o'

#colors
alias txtred=$(tput setaf 1) # Red
alias txtgrn=$(tput setaf 2) # Green
alias txtylw=$(tput setaf 3) # Yellow
alias txtblu=$(tput setaf 4) # Blue
alias txtpur=$(tput setaf 5) # Purple
alias txtcyn=$(tput setaf 6) # Cyan
alias txtwht=$(tput setaf 7) # White
alias txtrst=$(tput sgr0) # Text reset

alias txtund=$(tput sgr 0 1)          # Underline
alias txtbld=$(tput bold)             # Bold

